name: Maven Package

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Compile Source Code
      run: mvn compile

    - name: Execute Unit Tests
      run: mvn test

    - name: Verify Code Coverage
      run: mvn verify

    - name: Deploy Snapshot to GitHub Packages
      if: github.ref == 'refs/heads/main' && success()  # Only deploy from the main branch (refs/heads/main) and if all previous steps succeed (success())
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/inestrivino/JavaPandas
      env:
        GITHUB_TOKEN: ${{ github.token }}

